version: "3.9"

services:
  app:
    container_name: eks-devops-app-compose

    build:
      context: ./app

    image: eks-devops-app:v3

    ports:
      - "3000:3000"

    environment:
      APP_MESSAGE: "Hello from Docker Compose"

    restart: unless-stopped
