replicaCount: 1

image:
  repository: jadon3107/eks-devops-app
  tag: v3
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30081

persistence:
  enabled: false
