replicaCount: 3

image:
  repository: jadon3107/eks-devops-app
  tag: v3
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30082

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 2Gi
