replicaCount: 3

image:
  repository: eks-devops-app
  tag: v2
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30082

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 2Gi
